### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Lockhead** [dominicsayers/isemail#15]
Or is their still interest in developing it?

**Comment by dominicsayers** [comment]
The RFCs concerning internationalised email addresses postdate this work, so it could be brought up-to-date in that respect. Other than that, the RFCs are what they are so there's no functional need for this project to change.

My coding style improved considerably after I did this, so some refactoring is in order.

Versions of this project for other programming languages and frameworks have been made, and it would be nice to abstract the test suite so it could be consumed by multiple development environments.

I don't have time at the moment to attempt any of this, but I'll happily accept good pull requests.
