### ISSUE TITLE
Publish as package

### ISSUE THREAD

**Issue by Bonscho** [dominicsayers/isemail#16]
Could you please publish the repo as package at packagist.org?
That would be a great improvement on handling your project as dependency for us.

**Comment by dominicsayers** [comment]
Done, I think. Can you check?

**Comment by Bonscho** [comment]
Yep. I checked. You need to push a `release` (tag) representing a [semantic version](https://getcomposer.org/doc/articles/versions.md) (f.e. `1.0.0` or similar) and have the packagist service for your github repo installed. It can be found under settings, integration and services. 

Then a new release version is hooked over to packagist so we do not need to install the version `dev-master` and you could easily tag new releases allowing dependants to update while keeping their applications stable and compatible.

**Comment by dominicsayers** [comment]
Also done (I think)

**Comment by Bonscho** [comment]
Yep. Works like a charme. Thanks a lot. This step simplifies the usage of your library for us.
